server:
  port: 8200

spring:
  application:
    name: ingot-service-gateway
  redis:
    password: ${REDIS_PASSWORD:ingotredis}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:ingot-nacos}:${NACOS_PORT:8848}
        namespace: ingot
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml