
# 日志等级
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug
    com.alibaba.nacos.client.naming: info
    org.springframework.aop: DEBUG