apply from: "${project.getRootDir().path}/config/library-base.gradle"

dependencies {
    testImplementation(deps.spring.spring_boot.test)
    testImplementation project(ingot.framework_data_redis)
    testRuntimeOnly(deps.junit.platform_launcher)
    implementation project(ingot.framework_core)
    api(deps.aj_captcha)

    compileOnly project(ingot.framework_security_common)
    compileOnly(deps.spring.security_web)
    compileOnly(deps.spring.spring_boot.data_redis_starter)
    compileOnly(deps.spring.spring_boot.spring_boot_autoconfigure)
    compileOnly(deps.spring.framework_spring_webflux)
    compileOnly(deps.spring.framework_webmvc)
    compileOnly(deps.jakarta_servlet_api)
}

test { useJUnitPlatform() }
