
# 日志等级
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    com.alibaba.nacos.client.naming: info

ingot:
  security:
    oauth2:
      auth:
        loginFormUrl: http://127.0.0.1:1798/oauth2/challenge

springdoc:
  api-docs:
    enabled: true