apply from: "${project.getRootDir().path}/config/library-base.gradle"

dependencies {
    api project(ingot.framework_security_account_core)
    api project(ingot.security_api)
    implementation project(ingot.framework_data_mybatis_common)
    implementation project(ingot.framework_security_recording)
    implementation project(ingot.framework_security_event_store_mysql)
    implementation project(ingot.framework_security_event_transport_feign)
    implementation(deps.mybatis.plus_starter)
    implementation project(ingot.framework_tss_spring)

    compileOnly(deps.spring.spring_cloud.openfeign_starter)
    compileOnly(deps.lombok)
    annotationProcessor(deps.lombok)

    testImplementation(deps.spring.spring_boot.test)
    testImplementation(deps.h2)
}

test {
    useJUnitPlatform()
}
