apply from: "${project.getRootDir().path}/config/library-base.gradle"

dependencies {
    implementation(deps.spring.spring_boot.spring_boot_autoconfigure)
    implementation(deps.mybatis.plus_spring)
    implementation(deps.mybatis.plus_join)
    implementation project(ingot.framework_data_mybatis_common)
    implementation project(ingot.framework_core)
    implementation project(ingot.framework_security_common)
    implementation project(ingot.framework_cache)
    implementation project(ingot.framework_event_bus)
    implementation project(ingot.pms_api)
    implementation(deps.spring.framework_webmvc)

    compileOnly(deps.spring.spring_cloud.openfeign_starter)
    compileOnly(deps.jackson.data_bind)
    compileOnly(deps.jackson.annotation)
    compileOnly(deps.spring.spring_boot.data_redis_starter)
    compileOnly(deps.jakarta_servlet_api)

    testImplementation(deps.junit.jupiter)
    testRuntimeOnly(deps.junit.platform_launcher)
}

test {
    useJUnitPlatform()
}
