apply from: "${project.getRootDir().path}/config/library-base.gradle"

dependencies {

    api project(ingot.framework_core)
    api project(ingot.framework_security_config)
    api(deps.spring.spring_boot.security_starter)
    api(deps.spring.security_oauth2_core)
    api(deps.spring.security_oauth2_jose)
    api(deps.spring.security_oauth2_resource_server)

    implementation(deps.spring.framework_webmvc)
    implementation(deps.spring.spring_boot.data_redis_starter)
    
    // User-Agent 解析库
    implementation(deps.useragent_parse)

    compileOnly(deps.jakarta_servlet_api)
    compileOnly(deps.spring.spring_boot.actuator_autoconfigure)
    compileOnly(deps.spring.spring_boot.actuator_starter)

    testImplementation(deps.spring.spring_boot.test)
    testImplementation(deps.spring.spring_boot.actuator_starter)
    testImplementation(deps.jakarta_servlet_api)
    testCompileOnly(deps.lombok)
    testAnnotationProcessor(deps.lombok)
}

test {
    useJUnitPlatform()
}