apply from: "${project.getRootDir().path}/config/library-base.gradle"
dependencies {
    api project(ingot.framework_commons)
    api project(ingot.framework_data_mybatis_common)
    implementation project(ingot.framework_security_common)
    implementation project(ingot.framework_cache)
    implementation project(ingot.framework_event_bus)
    implementation project(ingot.iam_api)
    implementation project(ingot.framework_data_mybatis_scope)
    implementation(deps.jackson.data_bind)
    compileOnly(deps.spring.spring_boot.data_redis_starter)
    compileOnly(deps.spring.spring_cloud.openfeign_starter)
    implementation(deps.spring.spring_boot.spring_boot_autoconfigure)
    implementation(deps.spring.framework_webmvc)
    implementation project(ingot.framework_core)
    compileOnly(deps.jakarta_servlet_api)
    testRuntimeOnly(deps.jakarta_servlet_api)
    testImplementation(deps.junit.jupiter)
    testRuntimeOnly(deps.junit.platform_launcher)
}
test { useJUnitPlatform() }
